apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      environment: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: jenkins
        environment: dev
    spec:
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-pvc
      containers:
        - name: jenkins-container
          image: divyajeetsingh/jenkins-kubectl
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: jenkins-persistent-storage
            mountPath: /root/.jenkins/