apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins
    environment: dev
spec:
  type: NodePort
  selector:
    app: jenkins
    environment: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32600