FROM ubuntu:16.04
RUN apt-get update -y && apt-get install -y curl git wget openssh-server openjdk-8-jdk
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubect
RUN mkdir /var/run/sshd
RUN echo 'root:jenkins' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin
COPY ./ca.crt ./client.crt ./client.key ./config /.kube/
ENV KUBECONFIG="/.kube/config"
RUN chown -hR root:root /root/		&&	chown -hR root:root /.kube/
EXPOSE 22
CMD ["/usr/sbin/sshd" "-D"]
