apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: php-deployment
  labels:
    app: php
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      environment: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: php
        environment: dev
    spec:
      volumes:
      - name: php-persistent-storage
        persistentVolumeClaim:
          claimName: php-pvc
      containers:
        - name: php-container
          image: divyajeetsingh/php:latest
          ports:
            - containerPort: 80
          volumeMounts:
          - name: php-persistent-storage
            mountPath: /usr/src/myapp
