apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: php-pvc
  labels:
    app: php
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
