apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: php-svc
  labels:
    app: php
    environment: dev
spec:
  type: NodePort
  selector:
    app: php
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32500
